
services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=UnJ3nD3S3cR3t0MuyL4rg0YCompl3j0!2026
    volumes:
      - ./backend/db:/app/db
      - ./backend/uploads:/app/uploads
    command: npm start

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - api